### ISSUE TITLE
broken link: Overview_of_FOSS.md

### ISSUE THREAD

**Issue by brettsheffield** [fontfish/Wolf-and-Poems#1]
Nice work!

README.md contains a broken link to https://github.com/fontfish/Wolf-and-Poems/blob/master/Overview_of_FOSS.md

**Comment by danshearer** [comment]
Should that perhaps be https://github.com/fontfish/Wolf-and-Poems/blob/master/Thoughts_on_FOSS.md ?

**Comment by fontfish** [comment]
Thank you @brettsheffield and @danshearer . I've fixed the link, so will mark this as closed.
